# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: dotnet-guestbook-frontend"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicles-service
  labels:
    app: vehicles-service
    service: vehicles-service
    version: v1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicles-service
      service: vehicles-service
      version: v1

  template:
    metadata:
      labels:
        app: vehicles-service
        service: vehicles-service
        version: v1

    spec:
      containers:
      - image: pacco-vehicles-service:latest
        name: vehicles-service
        ports:
        - name: http-server
          containerPort: 80
        env:
          - name: ASPNETCORE_URLS
            value: http://*:80
          - name: ASPNETCORE_ENVIRONMENT
            value: k8s
        resources: {}
      restartPolicy: Always
